# Generated by Django 4.2.3 on 2023-07-26 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LODesigner', '0002_remove_project_png'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modes', models.IntegerField()),
                ('matrix', models.TextField()),
                ('inv', models.TextField()),
                ('result', models.TextField()),
                ('fidelities', models.TextField()),
                ('cgate_run_x', models.TextField()),
                ('cgate_run_y', models.TextField()),
                ('cgate_run_z', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LOConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LODevice',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('theta', models.CharField(max_length=50)),
                ('phi', models.CharField(max_length=50)),
                ('n', models.CharField(max_length=50)),
                ('input_type', models.CharField(default='0', max_length=50)),
                ('x', models.IntegerField(default=100)),
                ('y', models.IntegerField(default=100)),
                ('project_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LODesigner.project')),
            ],
        ),
    ]
